projects/mvc/razor-pages-mvc/Controllers/EntryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RazorPagesMvc.Data;
using System.Threading.Tasks;

namespace RazorPagesMvc.Controllers
{
    [Route("Mvc")]
    public class EntryController : Controller
    {
        private GuestbookContext _db;

        public EntryController(GuestbookContext db) => _db = db;

        [Route("Index")]
        public async Task<IActionResult> Index()
        {
            var entries = await _db.Entries.AsNoTracking().ToListAsync();
            return View(entries);
        }

        [HttpPost]
        [Route("Edit")]
        public async Task<IActionResult> Edit(Entry entry)
        {
            if (!ModelState.IsValid) return View("Edit", entry);

            _db.Attach(entry).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [Route("Edit")]
        public async Task<IActionResult> Edit(int id)
        {
            var entry = await _db.Entries.SingleOrDefaultAsync(e => e.Id == id);
            return View(entry);
        }

        [HttpPost]
        [Route("Create")]
        public async Task<IActionResult> Create(Entry entry)
        {
            if (!ModelState.IsValid) return View(entry);

            await _db.Entries.AddAsync(entry);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [Route("Create")]
        public IActionResult Create() => View();

        [HttpPost]
        [Route("Like")]
        public async Task<IActionResult> Like(int id)
        {
            var entry = await _db.Entries.SingleOrDefaultAsync(e => e.Id == id);
            entry.Likes += 1;
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

projects/mvc/razor-pages-mvc/Pages/RazorPages/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesMvc.Data;
using System.Threading.Tasks;

namespace RazorPagesMvcCrud.Pages
{
    public class CreateModel : PageModel
    {
        private readonly GuestbookContext _db;

        public CreateModel(GuestbookContext db) => _db = db;

        [BindProperty]
        public Entry Entry { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) return Page();

            _db.Entries.Add(Entry);
            await _db.SaveChangesAsync();
            return RedirectToPage("Index");
        }
    }
}

projects/mvc/razor-pages-mvc/Pages/RazorPages/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesMvc.Data;
using Microsoft.EntityFrameworkCore;

namespace RazorPagesMvcCrud.Pages
{
    public class EditModel : PageModel
    {
        private readonly GuestbookContext _db;

        public EditModel(GuestbookContext db) => _db = db;

        [BindProperty]
        public Entry Entry { get; set; }

        public async Task<IActionResult> OnGetAsync(int id)
        {
            Entry = await _db.Entries.FindAsync(id);

            if (Entry == null) return RedirectToPage("/Index");

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) return Page();

            _db.Attach(Entry).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return RedirectToPage("Index");
        }
    }
}

projects/mvc/razor-pages-mvc/Pages/RazorPages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesMvc.Data;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace RazorPagesMvcCrud.Pages
{
    public class IndexRazorPagesModel : PageModel
    {
        private readonly GuestbookContext _db;

        public IndexRazorPagesModel(GuestbookContext db) => _db = db;

        public IList<Entry> Entries { get; private set; }

        public async Task OnGetAsync()
        {
            Entries = await _db.Entries.AsNoTracking().ToListAsync();
        }

        public async Task<IActionResult> OnPostLikeAsync(int id)
        {
            var entry = await _db.Entries.FindAsync(id);
            entry.Likes += 1;
            await _db.SaveChangesAsync();
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostDeleteAsync(int id)
        {
            var entry = await _db.Entries.FindAsync(id);
            _db.Entries.Remove(entry);
            await _db.SaveChangesAsync();
            return RedirectToPage();
        }
    }
}

projects/mvc/razor-pages-mvc/Pages/RazorPages/Create.cshtml
@page
@model RazorPagesMvcCrud.Pages.CreateModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<html>
    <body>
        <p>Add new guestbook entry.</p>
        <div asp-validation-summary="All"></div>
        <form method="POST">
            <div>Name: <input asp-for="Entry.Content" /></div>
            <div>Email: <input asp-for="Entry.Email" /></div>
            <input type="submit" />
        </form>
    </body>
</html>

projects/mvc/razor-pages-mvc/Pages/RazorPages/Edit.cshtml
@page "{id:int}"
@model RazorPagesMvcCrud.Pages.EditModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<h1>Edit Guestbook Entry @Model.Entry.Id</h1>

<form method="post">
    <div asp-validation-summary="All"></div>
    <input asp-for="Entry.Id" type="hidden" />
    <input asp-for="Entry.Email" type="hidden" />
    <input asp-for="Entry.Likes" type="hidden" />
    <div>
        <label asp-for="Entry.Content"></label>
        <div>
            <input asp-for="Entry.Content" />
            <span asp-validation-for="Entry.Content"></span>
        </div>
    </div>

    <div>
        <button type="submit">Save</button>
    </div>
</form>

projects/mvc/razor-pages-mvc/Pages/RazorPages/Index.cshtml
@page
@model RazorPagesMvcCrud.Pages.IndexRazorPagesModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<h1>Razor Pages Implementation</h1>
<p>Add your entry to guestbook.</p>
<form method="post">
    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Email</th>
            <th>Content</th>
            <th>Likes</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var entry in Model.Entries)
        {
            <tr>
                <td>@entry.Id</td>
                <td>@entry.Email</td>
                <td>@entry.Content</td>
                <td>@entry.Likes</td>
                <td>
                    <button type="submit" asp-page-handler="like" 
                            asp-route-id="@entry.Id">like</button>
                    <a asp-page="./Edit" asp-route-id="@entry.Id">edit</a>
                </td>
            </tr>
        }
        </tbody>
    </table>
    <a asp-page="./Create">Create</a>
</form>

<p>Go back to <a href="/Index">Index</a></p>